title: Pup

description: Universal Process Manager

remote_theme: just-the-docs/just-the-docs

url: https://hexagon.github.io/pup

aux_links:
  GitHub Repository: https://github.com/hexagon/pup
  Deno Library: https://deno.land/x/pup

plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  
# color_scheme: dark
